name = "github-theme"
display-name = "GitHub Light"
description = "GitHub Light Theme"
version = "0.1.1"
author = "jsanchezba"
repository = "https://github.com/jsanchezba/lapce-github-theme"
color-themes = ["github-light.toml"]
icon = "github.png"